### PR TITLE
Citation modal

### PR DESCRIPTION
**Pull request by Joozty**
@viktor-yakubiv Citation generation is not bulletproof.  I will need to study more our API code (for example internal API sends the whole date, not just year. I am not sure if this happens always or not.) Take this code more like a starting point.  I am not sure even about whether I followed citation norms because on every page I visited there were different recommendations on how to use particular citation norm.

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
You can fallback to calling Crossredf API if DOI exists otherwise disable citing button. This is how it works on production now.

Also, you may consider a little bit easier way: use you solution but if something goes wrong disable the feature.

I will take a look at the code on Tuesday (we have a holiday tomorrow).

Thank you for contributing!

**Comment by Joozty** [comment]
> Also, you may consider a little bit easier way: use you solution but if something goes wrong disable the feature.

It won't crash it's just I am not sure whether citations are generated correctly. I am a little bit lost in all of the norms.


> You can fallback to calling Crossref API if DOI exists otherwise disable citing button. This is how it works on production now.

What for? Can you point me to documentation or something?

Also, I am not sure what should happen when a user clicks on BibTeX, should the code be copied into the clipboard? And what is EndNote what it is good for?

**Comment by viktor-yakubiv** [comment]
What did happen with this? Should I review it?

**Comment by Joozty** [comment]
Please don't. It needs to rebase and somebody to check if citations are generated correctly according to norms. :(

**Comment by Joozty** [comment]
Closing as it needs complete rewriting.

**Pull request closed without merging**
